### ISSUE TITLE
AMP Pages Ranking Down

### ISSUE THREAD

**Issue by azimrazvi** [ampproject/meta#6]
Hi All,

I was wondering why my AMP pages traffic gone down from last week and I found below page updates related to AMP Pages. I would request you to please review our AMP page - http://www.india.com/education/ibps-po-exam-2018-admit-card-released-download-hall-ticket-from-ibps-in-3350710/amp/

and let me know what should I change and update.

Thanks in Advance

https://github.com/ampproject/meta/pull/1

Regards,
Azeen

**Comment by mrjoro** [comment]
Hi @azimrazvi; please use the [support options](https://www.ampproject.org/support/developer/get_support) described on ampproject.org for help with this issue.

If your issue is with traffic from a specific search engine, please look for the support options that that search engine provides.  For example if your issue is with traffic from Google Search Google has an [AMP forum](https://productforums.google.com/forum/#!topicsearchin/webmasters/category$3Aaccelerated-mobile-pages-amp%7Csort:relevance%7Cspell:false).
